#ifndef _CONTEXT_CODES_INCLUDED_
#define _CONTEXT_CODES_INCLUDED_

namespace DSight {
	enum ContextCode {
		DSIGHT_CONTEXT_GLFW3,
		DSIGHT_CONTEXT_GTK2,
		DSIGHT_CONTEXT_GTK3,
		DSIGHT_CONTEXT_SDL1,
		DSIGHT_CONTEXT_SDL2
	};
}
#endif
